---

# Execute group of tasks

- name: playbook - Execute multiple task 
  hosts: helper
  gather_facts: true


  ## Execute multiple tasks 
  tasks:

    - name: playbook - execute task 1
      shell: echo 'this is a loose task 1'
  
    - name: playbook - execute task 2
      shell: echo 'this is a loose task 2'


# Execute group of tasks

- name: playbook - Execute multiple task 
  hosts: all
  gather_facts: true


  ## Execute multiple tasks
  tasks:

    - name: playbook - execute task 1
      shell: echo 'this is a loose task 1'
  
    - name: playbook - execute task 2
      shell: echo 'this is a loose task 2'

## A voir la notion de block:


## Execute multiple roles

- name: playbook - execute multiple Role 1
  hosts: localhost
  
  roles:
    - common

- name: playbook - execute multiple Role 2
  hosts: localhost
  
  roles:
    - role_1
  
  tasks:
    - shell: echo 'this is a loose task 1'


