---
all:
  hosts:
    helper: 
      ansible_connection: local 
    db1: 
      ansible_connection: local 
      service_port: 7444      
    app1: 
      ansible_connection: local 
      service_port: 80      
    app2: 
      ansible_connection: local 
      service_port: 80      
    web[1:3]: 
      ansible_connection: local
      service_port: 443 

  # Variable for all hosts  
  vars:
    ntp_server: ntp.all.example.com

  children:
    helpers:
      helper:
    
    dbs:
      hosts:
        db1: 

    apps:
      hosts:
        app1:
        app2:
      # Variable for all apps hosts
      vars:
        ntp_server: ntp.apps.example.com   

    webs:
      hosts:
        web[1:3]: 


