all:
  hosts:
    helper: 
      ansible_connection: local 
    db1: 
      ansible_connection: local       
    app1: 
      ansible_connection: local 
    web1: 
      ansible_connection: local 

  children:
    helpers:
      helper:
    
    dbs:
      hosts:
        db1: 

    apps:
      hosts:
        app1: 

    webs:
      hosts:
        web1: 


